export { default as Contact } from "../pages/Contact/Contact"
export { default as Connect } from "../pages/Connect/Connect"
export { default as Dashboard } from "../pages/Dashboard/Dashboard"
export { default as Home } from "../pages/Home/Home"
export { default as Jobs } from "../pages/Jobs/Jobs"
export { default as LoginSignup } from "../pages/LoginSignup/LoginSignup"
export { default as Internships } from "../pages/Internships/Internships"